spring:
  application:
    name: chatProject

  datasource:
    url: jdbc:h2:tcp://localhost/~/chat
    username: sa
    password:
    driver-class-name: org.h2.Driver

  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 2000

logging.level:
  org.hibernate.SQL: debug

chat:
  room:
    max_user_count: 100